version: '3.8'

services:
  # Health Chatbot API service
  health-chatbot:
    build: .
    ports:
      - "8000:8000"  # API chạy trên port 8000
    env_file:
      - .env
    environment:
      - ENV=development
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
